#!/bin/sh

# bootstrap the build when checking out from CVS

# dodgy hack to use gmake if we're on bsd systems
if [ -x /usr/local/bin/gmake ]; then
	MAKE=/usr/local/bin/gmake
else
	MAKE=make
fi

if [ "$1" = "clean" ]; then
	# clean up junk
	
	if [ -f Makefile ]; then 
		$MAKE distclean
	fi
	find . -name Makefile.in -print | xargs rm -f
	rm -f aclocal.m4 install-sh missing mkinstalldirs \
	      stamp-h.in tags configure config.*
	rm -rf autom4te.cache

else

	aclocal
	autoheader
	automake --foreign --add-missing --copy
	autoconf

fi
